<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="Devlead.Console.props" />

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <OutputType Condition="'$(Configuration)'=='Debug'">Exe</OutputType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon/devlead.console.png</PackageIcon>
    <IsPackable>true</IsPackable>
    <SourcePackRoot>Devlead/Console</SourcePackRoot>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\Devlead.Console.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Microsoft.Extensions.DependencyInjection.Extensions" />
    <Using Include="Microsoft.Extensions.Configuration" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
    <Using Include="Microsoft.Extensions.Logging" />
    <Using Include="Microsoft.Extensions.Options" />
    <Using Include="Spectre.Console" />
    <Using Include="Spectre.Console.Cli" />
    <Using Include="Spectre.Console.Cli.Extensions.DependencyInjection" />
    <Using Include="System.Globalization" />
    <Using Include="System.Net" />
    <Using Include="System.Text" />
    <Using Include="System.Text.Json" />
    <Using Include="System.Text.Json.Serialization" />
    <Using Include="Devlead.Console.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Devlead.SourcePack" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <SourcePackFile Include="../../icon/LICENSE.md" Kind="Metadata" PackagePath="icon/LICENSE.md" />
    <SourcePackFile Include="../../icon/devlead.console.png" Kind="Metadata" PackagePath="icon/devlead.console.png" />
    <SourcePackFile Include="../../README.md" Kind="Metadata" />
    <SourcePackFile Include="Devlead.Console.props" Kind="Build" />
    <SourcePackFile Include="Devlead.Console.targets" Kind="Build" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' != 'Debug'">
    <Compile Remove="Program.cs" />
    <Compile Remove="Extensions\ServiceCollectionExtensions.cs" />
  </ItemGroup>

  <Import Project="Devlead.Console.targets" />
</Project>
